#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=67
STOP=01
DEPEND=moonraker
USE_PROCD=1
#FIXME: make this detected and dynamic
PROG=/mnt/UDISK/moonraker-obico-env/bin/python
USERDATA=/mnt/UDISK/printer_data
PRINTER_CONFIG_DIR=$USERDATA/config
PRINTER_CUSTOM_CFG=$PRINTER_CONFIG_DIR/moonraker-obico.cfg
OOM_ADJ=-17

start_service() {
    procd_open_instance
    procd_set_param env HOME=/root
    #FIXME: make this detected and dynamic
    procd_set_param env PYTHONPATH=/mnt/UDISK/moonraker-obico
    procd_set_param working_dir /mnt/UDISK/moonraker-obico
    procd_set_param oom_adj $OOM_ADJ
    procd_set_param command $PROG -m moonraker_obico.app -c $PRINTER_CUSTOM_CFG
    procd_close_instance
}
